version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: Europe/Bucharest
    open-pull-requests-limit: 10
    target-branch: main